export const COUNTRIES: { code: string; name: string }[] = [
  { code: "CO001", name: "Afghanistan" },
  { code: "CO002", name: "Albania" },
  { code: "CO003", name: "Algeria" },
  { code: "CO004", name: "Andorra" },
  { code: "CO005", name: "Angola" },
  { code: "CO006", name: "Antigua and Barbuda" },
  { code: "CO007", name: "Argentina" },
  { code: "CO008", name: "Armenia" },
  { code: "CO009", name: "Australia" },
  { code: "CO010", name: "Austria" },
  { code: "CO011", name: "Azerbaijan" },
  { code: "CO012", name: "Bahamas" },
  { code: "CO013", name: "Bahrain" },
  { code: "CO014", name: "Bangladesh" },
  { code: "CO015", name: "Barbados" },
  { code: "CO016", name: "Belarus" },
  { code: "CO017", name: "Belgium" },
  { code: "CO018", name: "Belize" },
  { code: "CO019", name: "Benin" },
  { code: "CO020", name: "Bhutan" },
  { code: "CO021", name: "Bolivia" },
  { code: "CO022", name: "Bosnia and Herzegovina" },
  { code: "CO023", name: "Botswana" },
  { code: "CO024", name: "Brazil" },
  { code: "CO025", name: "Brunei" },
  { code: "CO026", name: "Bulgaria" },
  { code: "CO027", name: "Burkina Faso" },
  { code: "CO028", name: "Burundi" },
  { code: "CO029", name: "Cabo Verde" },
  { code: "CO030", name: "Cambodia" },
  { code: "CO031", name: "Cameroon" },
  { code: "CO032", name: "Canada" },
  { code: "CO033", name: "Central African Republic" },
  { code: "CO034", name: "Chad" },
  { code: "CO035", name: "Chile" },
  { code: "CO036", name: "China" },
  { code: "CO037", name: "Colombia" },
  { code: "CO038", name: "Comoros" },
  { code: "CO039", name: "Congo, Democratic Republic of the" },
  { code: "CO040", name: "Congo, Republic of the" },
  { code: "CO041", name: "Costa Rica" },
  { code: "CO042", name: "Croatia" },
  { code: "CO043", name: "Cuba" },
  { code: "CO044", name: "Cyprus" },
  { code: "CO045", name: "Czech Republic" },
  { code: "CO046", name: "Denmark" },
  { code: "CO047", name: "Djibouti" },
  { code: "CO048", name: "Dominica" },
  { code: "CO049", name: "Dominican Republic" },
  { code: "CO050", name: "Ecuador" },
  { code: "CO051", name: "Egypt" },
  { code: "CO052", name: "El Salvador" },
  { code: "CO053", name: "Equatorial Guinea" },
  { code: "CO054", name: "Eritrea" },
  { code: "CO055", name: "Estonia" },
  { code: "CO056", name: "Eswatini" },
  { code: "CO057", name: "Ethiopia" },
  { code: "CO058", name: "Fiji" },
  { code: "CO059", name: "Finland" },
  { code: "CO060", name: "France" },
  { code: "CO061", name: "Gabon" },
  { code: "CO062", name: "Gambia" },
  { code: "CO063", name: "Georgia" },
  { code: "CO064", name: "Germany" },
  { code: "CO065", name: "Ghana" },
  { code: "CO066", name: "Greece" },
  { code: "CO067", name: "Grenada" },
  { code: "CO068", name: "Guatemala" },
  { code: "CO069", name: "Guinea" },
  { code: "CO070", name: "Guinea-Bissau" },
  { code: "CO071", name: "Guyana" },
  { code: "CO072", name: "Haiti" },
  { code: "CO073", name: "Honduras" },
  { code: "CO074", name: "Hungary" },
  { code: "CO075", name: "Iceland" },
  { code: "CO076", name: "India" },
  { code: "CO077", name: "Indonesia" },
  { code: "CO078", name: "Iran" },
  { code: "CO079", name: "Iraq" },
  { code: "CO080", name: "Ireland" },
  { code: "CO081", name: "Israel" },
  { code: "CO082", name: "Italy" },
  { code: "CO083", name: "Jamaica" },
  { code: "CO084", name: "Japan" },
  { code: "CO085", name: "Jordan" },
  { code: "CO086", name: "Kazakhstan" },
  { code: "CO087", name: "Kenya" },
  { code: "CO088", name: "Kiribati" },
  { code: "CO089", name: "Korea, North" },
  { code: "CO090", name: "Korea, South" },
  { code: "CO091", name: "Kosovo" },
  { code: "CO092", name: "Kuwait" },
  { code: "CO093", name: "Kyrgyzstan" },
  { code: "CO094", name: "Laos" },
  { code: "CO095", name: "Latvia" },
  { code: "CO096", name: "Lebanon" },
  { code: "CO097", name: "Lesotho" },
  { code: "CO098", name: "Liberia" },
  { code: "CO099", name: "Libya" },
  { code: "CO100", name: "Liechtenstein" },
  { code: "CO101", name: "Lithuania" },
  { code: "CO102", name: "Luxembourg" },
  { code: "CO103", name: "Madagascar" },
  { code: "CO104", name: "Malawi" },
  { code: "CO105", name: "Malaysia" },
  { code: "CO106", name: "Maldives" },
  { code: "CO107", name: "Mali" },
  { code: "CO108", name: "Malta" },
  { code: "CO109", name: "Marshall Islands" },
  { code: "CO110", name: "Mauritania" },
  { code: "CO111", name: "Mauritius" },
  { code: "CO112", name: "Mexico" },
  { code: "CO113", name: "Micronesia" },
  { code: "CO114", name: "Moldova" },
  { code: "CO115", name: "Monaco" },
  { code: "CO116", name: "Mongolia" },
  { code: "CO117", name: "Montenegro" },
  { code: "CO118", name: "Morocco" },
  { code: "CO119", name: "Mozambique" },
  { code: "CO120", name: "Myanmar" },
  { code: "CO121", name: "Namibia" },
  { code: "CO122", name: "Nauru" },
  { code: "CO123", name: "Nepal" },
  { code: "CO124", name: "Netherlands" },
  { code: "CO125", name: "New Zealand" },
  { code: "CO126", name: "Nicaragua" },
  { code: "CO127", name: "Niger" },
  { code: "CO128", name: "Nigeria" },
  { code: "CO129", name: "North Macedonia" },
  { code: "CO130", name: "Norway" },
  { code: "CO131", name: "Oman" },
  { code: "CO132", name: "Pakistan" },
  { code: "CO133", name: "Palau" },
  { code: "CO134", name: "Palestine" },
  { code: "CO135", name: "Panama" },
  { code: "CO136", name: "Papua New Guinea" },
  { code: "CO137", name: "Paraguay" },
  { code: "CO138", name: "Peru" },
  { code: "CO139", name: "Philippines" },
  { code: "CO140", name: "Poland" },
  { code: "CO141", name: "Portugal" },
  { code: "CO142", name: "Qatar" },
  { code: "CO143", name: "Romania" },
  { code: "CO144", name: "Russia" },
  { code: "CO145", name: "Rwanda" },
  { code: "CO146", name: "Saint Kitts and Nevis" },
  { code: "CO147", name: "Saint Lucia" },
  { code: "CO148", name: "Saint Vincent and the Grenadines" },
  { code: "CO149", name: "Samoa" },
  { code: "CO150", name: "San Marino" },
  { code: "CO151", name: "São Tomé and Príncipe" },
  { code: "CO152", name: "Saudi Arabia" },
  { code: "CO153", name: "Senegal" },
  { code: "CO154", name: "Serbia" },
  { code: "CO155", name: "Seychelles" },
  { code: "CO156", name: "Sierra Leone" },
  { code: "CO157", name: "Singapore" },
  { code: "CO158", name: "Slovakia" },
  { code: "CO159", name: "Slovenia" },
  { code: "CO160", name: "Solomon Islands" },
  { code: "CO161", name: "Somalia" },
  { code: "CO162", name: "South Africa" },
  { code: "CO163", name: "South Sudan" },
  { code: "CO164", name: "Spain" },
  { code: "CO165", name: "Sri Lanka" },
  { code: "CO166", name: "Sudan" },
  { code: "CO167", name: "Suriname" },
  { code: "CO168", name: "Sweden" },
  { code: "CO169", name: "Switzerland" },
  { code: "CO170", name: "Syria" },
  { code: "CO171", name: "Taiwan" },
  { code: "CO172", name: "Tajikistan" },
  { code: "CO173", name: "Tanzania" },
  { code: "CO174", name: "Thailand" },
  { code: "CO175", name: "Timor-Leste" },
  { code: "CO176", name: "Togo" },
  { code: "CO177", name: "Tonga" },
  { code: "CO178", name: "Trinidad and Tobago" },
  { code: "CO179", name: "Tunisia" },
  { code: "CO180", name: "Turkey" },
  { code: "CO181", name: "Turkmenistan" },
  { code: "CO182", name: "Tuvalu" },
  { code: "CO183", name: "Uganda" },
  { code: "CO184", name: "Ukraine" },
  { code: "CO185", name: "United Arab Emirates" },
  { code: "CO186", name: "United Kingdom" },
  { code: "CO187", name: "United States" },
  { code: "CO188", name: "Uruguay" },
  { code: "CO189", name: "Uzbekistan" },
  { code: "CO190", name: "Vanuatu" },
  { code: "CO191", name: "Vatican City" },
  { code: "CO192", name: "Venezuela" },
  { code: "CO193", name: "Vietnam" },
  { code: "CO194", name: "Yemen" },
  { code: "CO195", name: "Zambia" },
  { code: "CO196", name: "Zimbabwe" },
];
